### ISSUE TITLE
 ラベルの位置がずれる

### ISSUE THREAD

**Issue by RosettaHalt** [phi-jp/tmlib.js#1]
同じブラウザでもOS環境によってラベルの位置がずれるみたい。
Chromeで見た時に
Snow LeopardとLionでズレるのを確認しました。

恐らくSnow Leopardだとずれてるみたい。

**Comment by phi-jp** [comment]
canvas の fillText や strokeText の最後の引数 `maxWidth` が, safari 系では効かないらしい.
いずれ効くようになる...はず...
