### ISSUE TITLE
tm.input.TouchのgetTouch()を呼び出すとエラーになる

### ISSUE THREAD

**Issue by ashel** [phi-jp/tmlib.js#106]
tmlibを使わせていただきまして、どうもありがとうございます。
tmlib0.2.0で、tm.input.TouchのgetTouch()を呼び出したところ、エラーが発生しました。
8459行目の

return this.touched != 0;

を

return this.touched;

と修正したところ、正常に動作するようになりましたので、報告させていただきます。

**Comment by phi-jp** [comment]
指摘ありがとうございます!

すいません, 私の環境では再現しないのですが
実際にそれが起きたコードって見ることできませんか?

**Comment by ashel** [comment]
すいません、私の方でも再現を試みたのですが、再現できませんでした。
何か勘違いをしていたようです…手数をおかけしてしまい、大変申し訳ありませんでした。
取り下げさせていただきます。

**Comment by phi-jp** [comment]
とんでもないですー^^
また気になることなどありましたら
気軽に issue 送ってください♪
