### ISSUE TITLE
JavaScript ファイルのAsset対応

### ISSUE THREAD

**Issue by fukuyama** [phi-jp/tmlib.js#146]
tm.util.Scriptで、スクリプトのロードが出来ますが、tm.asset.Loader 等のAssetとして
*.js ファイルを指定した場合にも、ロードできるようにして欲しいです。

**Comment by fukuyama** [comment]
とりあえず

``` JavaScript
tm.asset.Loader.register('js', function(path) {
  return tm.util.Script(src);
});
```

こんな感じとか

``` JavaScript
tm.asset.Loader.register('js', tm.util.Script.load);
```

これでも、Assetでロードできそう。
ただ、他のAssetと違って、tm.asset.Manager.get は使わない気がする。

tm.asset.Manager.get つかうなら require みたく、module を使えるようにするのかとかあるかも？
今の、script タグでロードするのがシンプルそうだけど…

.js をどちらで読み込むのが良いのか。

**Comment by phi-jp** [comment]
こんな感じでどうでしょう？
https://github.com/phi-jp/tmlib.js/pull/149

**Comment by fukuyama** [comment]
お早い対応ありがとうございます！

**Comment by phi-jp** [comment]
対応, merge したので close しますね♪
