### ISSUE TITLE
tm.app.BaseApp.prototype.popSceneのreturn値について

### ISSUE THREAD

**Issue by omatoro** [phi-jp/tmlib.js#39]
popScene関数を利用後、returnされる値はexitが呼ばれる予定のシーンとなっています。
私の感覚的にはpop後のシーンが取得できるのかと思っていましたが、この動作は仕様でしょうか。

pop後のシーンをreturnするのであれば、popSceneの戻り値は「e.target」になるかと思います。

**Comment by omatoro** [comment]
訂正です。

"私の感覚的にはpop後のシーンが取得できるのかと思っていましたが、この動作は仕様でしょうか。"
この部分は間違いです。
pop後のシーンが取得できた方が都合が良いから、という理由です。
以下のようなサンプルを作る際に、都合が良かったのでissueとして上げました。

http://jsdo.it/omatoro/kk9c/edit

**Comment by daishihmr** [comment]
横槍失礼します。

Array（というか一般的なスタック）のpush/popと同じふるまいなので、感覚的には現状で合ってると思いますよ。
もし、ご要望の機能（シーンスタック上のトップを捨てた後に新しくトップになったシーンを返す）が実装されるのであれば、popScene以外の名前をつけるのが良いかと思います。

**Comment by omatoro** [comment]
回答頂きありがとうございます。
popSceneを行う処理は、ほとんどはPauseシーンなどpushしたシーン内にて行う上(thisで取得できる)、
popScene後はシーンが削除されるため、取得できてもあまり意味がないのかなと感じました。
削除時に実行したい処理があれば、シーンクラスにてexitイベントに記述すれば良いとも思いますし。

そのため、直感とは反するものの、実装しても問題ないのかなと感じた次第です。
daishihmr様がおっしゃる通りだとも思いますので、是非ご一考ください。

**Comment by phi-jp** [comment]
omatoro san 質問ありがとうございます.
daishi san 回答ありがとうございます.

daishi さんの言うとおり, popScene の振る舞いを変えるのはイケてない気がします.
popScene 直後に currentScene でアクセスすればおそらくやりたいことはやれるかと思います.

**Comment by omatoro** [comment]
popScene直後に、app.currentSceneで同様の動作ができることを確認しました。
daishihmr様、phi1618様 ありがとうございました。
