### ISSUE TITLE
衝突判定の種類(円、矩形など)を自動判定するようにしてほしい

### ISSUE THREAD

**Issue by omatoro** [phi-jp/tmlib.js#40]
GlossyButtonクラスなどのinteractionオブジェクトにて以下の情報を設定しています。

``` javascript
this.interaction.enabled = true;
this.interaction.boundingType = "rect";
```

この情報を利用して、isHitPoint関数での衝突判定を自動選択してほしいです。

isHitPointCircle関数とisHitPointRect関数は別途用意する形になりますが、簡易的な衝突判定としてisHitPoint関数を用意しているのであれば有効な実装だと思います。

よろしくお願いします。

**Comment by phi-jp** [comment]
こんな感じでどうでしょう？

https://github.com/phi1618/tmlib.js/commit/2f127c086aa431418187013afbc9a3d978afe764

`boundingType`, `checkHierarchy` の値に応じて `isHitPoint` の
判定方法が切り替わるようになっています.

`Interaction` も連動してこの `isHitPoint` を使うよう修正してあります.

これ見ればなんとなく使い方がわかるかと思います.
http://phi1618.github.com/tmlib.js/test/app/interaction.html

これで問題なければ `isHitElement` の方も同じ対応をしようと考えています.

**Comment by omatoro** [comment]
完璧っす！
ありがとうございます。

**Comment by phi-jp** [comment]
そんじゃ閉じときますね.
