### ISSUE TITLE
Sprite の引数について再考

### ISSUE THREAD

**Issue by phi-jp** [phi-jp/tmlib.js#56]
↓今

```
var sprite = tm.app.Sprite(幅, 高さ, "画像名");
```

↓Sprite の引数を一個でも ok にする

```
var sprite = tm.app.Sprite("画像名");
```

画像のみ渡された場合はその画像のオリジナルサイズを
幅, 高さとしてとりあえず割り当てる.

その後変更可能.

って考えると, sprite の第一引数って画像じゃね？って思ってきた.

```
var sprite = tm.app.Sprite("画像名", 幅, 高さ);
```

**Comment by daishihmr** [comment]
ユーザーがSpriteを使う最初の動機が「絵を出したい！」だとしたら, その方が自然なのだろうな～と思います.

「画像は準備できてないけど、とりあえず四角を出して代用だ！」と考えている場合だとしても, tmlib.jsにはShape系が豊富にあるので問題ないと思います.

**Comment by RosettaHalt** [comment]
それでいいと思う。
高さと幅は指定する必要ないことも多いし後から変えれるし問題ないと思う。

**Comment by omatoro** [comment]
今まで気が付かなかったのが不思議。
賛成です。

**Comment by phi-jp** [comment]
そうですよね.

なんで (width, height, image) にしちゃったんだろ?w
修正します!!

**Comment by phi-jp** [comment]
done
