### ISSUE TITLE
2回目のLoadingSceneの呼び出しでnextSceneへreplaceされずにハングアップする

### ISSUE THREAD

**Issue by omatoro** [phi-jp/tmlib.js#61]
いつもお世話になっています。
表題の通り、2回目のLoadingSceneの呼び出しでnextSceneへreplaceされずにハングアップします。
tm.asset.AssetManager.onloadに登録している処理が、1回目のローディング完了時点でしか呼び出されないためではないかと思います。

以上、よろしくお願いします。

**Comment by phi-jp** [comment]
tm.asset.Loader では改修済みなので close します!!
